name: Snyk Executable Full plat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test and build
    environment: snyk-npm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Setup Snyk + snyk-to-html
      run: |
        curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x ./snyk
        ./snyk auth 4d601f86-ebd7-4615-9dc3-fea4cfcd957a
    - name: Snyk Open Source # For testing and failing please add snyk test before snyk cmonitor
      run: |
        ./snyk test || true 
    - name: Snyk Code # Remove || true to fail if there are vulnerabilities
      run: |
        ./snyk code test || true 
    - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
      run: |
        docker build . -t yourimage:tag
        ./snyk container test yourimage:tag --file=Dockerfile || true
    - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
      run: |
        /.snyk iac test || true
